version: '3.9'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-lm
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  backend:
  frontend:
