name: GitHub Pages Deploy
on:
  push:
    branches:
      - develop
    paths:
      - ./src/stories/**
      - .storybook/**
jobs:
  Deploy-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ./.nvmrc
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: export PUBLIC_URL=https://kjek.github.io/vad-ater-vi
      - name: Install dependencies
        run: |
          yarn
      - name: Build storybook
        run: |
          yarn storybook:build
      - name: Deploy using gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
      - run: echo "This job's status is ${{ job.status }}."
